// Code generated by protoc-gen-go. DO NOT EDIT.
// source: common/common.proto

package common // import "github.com/EGT-Ukraine/go2gql/testdata/common"

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CommonEnum int32

const (
	CommonEnum_CommonEnumVal0 CommonEnum = 0
	CommonEnum_CommonEnumVal1 CommonEnum = 1
)

var CommonEnum_name = map[int32]string{
	0: "CommonEnumVal0",
	1: "CommonEnumVal1",
}
var CommonEnum_value = map[string]int32{
	"CommonEnumVal0": 0,
	"CommonEnumVal1": 1,
}

func (x CommonEnum) String() string {
	return proto.EnumName(CommonEnum_name, int32(x))
}
func (CommonEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_common_44a7a018c771cd63, []int{0}
}

// Service, which do smth
type CommonMessage struct {
	Scalar               int32    `protobuf:"varint,1,opt,name=scalar,proto3" json:"scalar,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CommonMessage) Reset()         { *m = CommonMessage{} }
func (m *CommonMessage) String() string { return proto.CompactTextString(m) }
func (*CommonMessage) ProtoMessage()    {}
func (*CommonMessage) Descriptor() ([]byte, []int) {
	return fileDescriptor_common_44a7a018c771cd63, []int{0}
}
func (m *CommonMessage) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CommonMessage.Unmarshal(m, b)
}
func (m *CommonMessage) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CommonMessage.Marshal(b, m, deterministic)
}
func (dst *CommonMessage) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CommonMessage.Merge(dst, src)
}
func (m *CommonMessage) XXX_Size() int {
	return xxx_messageInfo_CommonMessage.Size(m)
}
func (m *CommonMessage) XXX_DiscardUnknown() {
	xxx_messageInfo_CommonMessage.DiscardUnknown(m)
}

var xxx_messageInfo_CommonMessage proto.InternalMessageInfo

func (m *CommonMessage) GetScalar() int32 {
	if m != nil {
		return m.Scalar
	}
	return 0
}

func init() {
	proto.RegisterType((*CommonMessage)(nil), "common.CommonMessage")
	proto.RegisterEnum("common.CommonEnum", CommonEnum_name, CommonEnum_value)
}

func init() { proto.RegisterFile("common/common.proto", fileDescriptor_common_44a7a018c771cd63) }

var fileDescriptor_common_44a7a018c771cd63 = []byte{
	// 151 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4e, 0xce, 0xcf, 0xcd,
	0xcd, 0xcf, 0xd3, 0x87, 0x50, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x6c, 0x10, 0x9e, 0x92,
	0x3a, 0x17, 0xaf, 0x33, 0x98, 0xe5, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x2a, 0x24, 0xc6, 0xc5,
	0x56, 0x9c, 0x9c, 0x98, 0x93, 0x58, 0x24, 0xc1, 0xa8, 0xc0, 0xa8, 0xc1, 0x1a, 0x04, 0xe5, 0x69,
	0x99, 0x70, 0x71, 0x41, 0x14, 0xba, 0xe6, 0x95, 0xe6, 0x0a, 0x09, 0x71, 0xf1, 0x21, 0x78, 0x61,
	0x89, 0x39, 0x06, 0x02, 0x0c, 0x18, 0x62, 0x86, 0x02, 0x8c, 0x4e, 0x06, 0x51, 0x7a, 0xe9, 0x99,
	0x25, 0x19, 0xa5, 0x49, 0x7a, 0xc9, 0xf9, 0xb9, 0xfa, 0xc5, 0x89, 0x25, 0xa5, 0x45, 0x79, 0x26,
	0xa9, 0x45, 0xfa, 0x60, 0x47, 0x18, 0xa5, 0x17, 0xe6, 0xe8, 0x97, 0xa4, 0x16, 0x97, 0xa4, 0x24,
	0x96, 0x24, 0x42, 0x9d, 0x97, 0xc4, 0x06, 0x96, 0x32, 0x06, 0x04, 0x00, 0x00, 0xff, 0xff, 0x92,
	0xef, 0xd2, 0xc8, 0xb6, 0x00, 0x00, 0x00,
}
